---
- hosts: localhost
  name: install asdf
  tasks:
  - name: clone repo
    ansible.builtin.git:
      repo: "https://github.com/asdf-vm/asdf.git"
      dest: "{{ansible_user_dir }}/.asdf"
      version: v0.11.3
      clone: true
      force: true


