---
- hosts: localhost
  name: install basic apps
  tasks:
  - name: instalable with package
    ansible.builtin.apt:
      name: 
        - build-essential
        - libxcb-keysyms1-dev 
        - libpango1.0-dev 
        - libxcb-util0-dev 
        - libxcb-icccm4-dev
        - libyajl-dev 
        - libstartup-notification0-dev 
        - libxcb-randr0-dev 
        - libev-dev 
        - libxcb-cursor-dev 
        - libxcb-xinerama0-dev 
        - libxcb-xkb-dev 
        - libxkbcommon-dev 
        - libxkbcommon-x11-dev 
        - autoconf 
        - libxcb-xrm0 
        - libxcb-xrm-dev 
        - automake 
        - libxcb-shape0-dev
        - cmake 
        - cmake-data 
        - libcairo2-dev 
        - libxcb1-dev 
        - libxcb-ewmh-dev 
        - libxcb-icccm4-dev 
        - libxcb-image0-dev 
        - libxcb-randr0-dev 
        - libxcb-util0-dev 
        - libxcb-xkb-dev 
        - pkg-config 
        - xcb-proto 
        - libxcb-xrm-dev 
        - libasound2-dev 
        - libmpdclient-dev 
        - libiw-dev 
        - libcurl4-openssl-dev 
        - libpulse-dev 
        - libxcb-composite0-dev 
        - xcb 
        - libxcb-ewmh2
      state: present
    become: yes
